### ISSUE TITLE
Could you please share the dataset？

### ISSUE THREAD

**Issue by JiahongWu1995** [V-Sekai-fire/meshgpt-dataset-02#1]
Hello, could you please share the dataset under the/content/drive/MyDrive path? Thank you very much!

**Comment by fire** [comment]
Sorry I cannot.

Please download and assemble your datasets using https://github.com/V-Sekai-fire/Objaverse-downloader.

You can also use any dataset you want.

**Comment by fire** [comment]
We also have some opensource datsets like:

* https://github.com/V-Sekai/V-Sekai.blue-tin-fox-models
* https://github.com/V-Sekai-fire/mesh-mille-mire-feuille
* https://github.com/V-Sekai-fire/mesh-human-base-mesh-1-1

However you must trim your datasets so the meshes are around 200 to 1000 triangles.
